name: secret validation

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
              env:
                TITLE: ${{ secret.GITHUB }}
              run: |
                 if [[ "$TITLE" =~ ^crnic ]]; then
                 echo "Token Valido"
                 exit 0
                 else
                 echo "Token INvalido"
                 exit 1
                 fi
    
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
