name: secret validation

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Validar secret
      env:
          TITLE: ${{ secrets.GITHUB }}
      run: |
        if [[ "$TITLE" =~ ^crnic ]]; then
        echo "Token Valido"
        exit 0
        else
        echo "Token INvalido"
        exit 1
        fi
          
    - name: Imprimir mensaje desde reusable-lab.yml
      run: echo "Este es un mensaje desde el flujo de trabajo reusable-lab.yml"
